"""Build the supervisor status deck from scratch, one function per slide.

Every slide is constructed with the native python-pptx API (add_slide on the
Blank layout + add_shape / add_textbox / add_picture) -- no XML tree-copy, no
binary patching -- so PowerPoint opens it without a repair prompt and the deck
is fully reproducible from source.

Figures come from Codebase/figures/ (regenerated by make_comparison_figures.py,
make_rq4_figure.py, make_scorecard.py) and Codebase/figures/deck/ (the two
custom diagrams -- pipeline, exploit -- extracted from the 28 Aug deck).

    python -m qbbr.scripts.make_status_deck   # -> ../qbbr_status_2026-09-04.pptx
"""
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR
from pptx.util import Inches, Pt

ROOT = Path(__file__).resolve().parent.parent.parent   # Codebase/
FIG = ROOT / "figures"
DECK = ROOT / "figures" / "deck"
OUT = ROOT.parent / "qbbr_status_2026-09-04.pptx"

EMU_W, EMU_H = Inches(13.333), Inches(7.5)
NAVY = RGBColor(0x1F, 0x2A, 0x44)
INK = RGBColor(0x20, 0x24, 0x2C)
GREY = RGBColor(0x6B, 0x72, 0x80)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GREEN = RGBColor(0x2F, 0x7A, 0x2F)
AMBER = RGBColor(0xB0, 0x5A, 0x00)
BLUE = RGBColor(0x2B, 0x5C, 0xA8)
CALLOUT_BG = RGBColor(0xEA, 0xF0, 0xF8)

FOOT_MAIN = "qbbr   ·   supervisor status   ·   {date}                    {n} / 8"
FOOT_APX = "qbbr   ·   supervisor status   ·   {date}                    appendix"
FOOT_UPD = "qbbr   ·   update since 28 Aug status   ·   4 Sep 2026"


# ----------------------------------------------------------------- helpers
def _tb(slide, x, y, w, h):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    box.text_frame.word_wrap = True
    return box


def _run(para, text, size, *, bold=False, italic=False, color=INK):
    r = para.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.italic = italic
    r.font.color.rgb = color
    return r


def header(slide, title_text):
    bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, EMU_W, Inches(1.0))
    bar.fill.solid()
    bar.fill.fore_color.rgb = NAVY
    bar.line.fill.background()
    bar.shadow.inherit = False
    t = _tb(slide, 0.55, 0.05, 12.3, 0.9)
    t.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    _run(t.text_frame.paragraphs[0], title_text, 23, bold=True, color=WHITE)


def caption(slide, text, y=1.05):
    c = _tb(slide, 0.57, y, 12.3, 0.34)
    _run(c.text_frame.paragraphs[0], text, 11, italic=True, color=GREY)


def footer(slide, text):
    f = _tb(slide, 0.55, 7.14, 12.3, 0.28)
    _run(f.text_frame.paragraphs[0], text, 9, color=GREY)


def bullets(slide, x, y, w, h, lines, size=12):
    tf = _tb(slide, x, y, w, h).text_frame
    for i, entry in enumerate(lines):
        text, kw = (entry if isinstance(entry, tuple) else (entry, {}))
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(6)
        _run(p, "•  " + text, size, color=kw.get("color", INK), bold=kw.get("bold", False))


def pic(slide, path, x, y, w, aspect):
    slide.shapes.add_picture(str(path), Inches(x), Inches(y), Inches(w),
                             int(Inches(w) / aspect))


def new_slide(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])   # Blank


# ----------------------------------------------------------------- slides
def slide01(prs):
    s = new_slide(prs)
    t = _tb(s, 0.85, 0.80, 11.7, 0.9)
    _run(t.text_frame.paragraphs[0], "The Limits of a Single Lever", 34, bold=True, color=NAVY)
    sub = _tb(s, 0.87, 1.75, 11.6, 0.4)
    _run(sub.text_frame.paragraphs[0],
         "qbbr — learned pacing_gain adaptation for BBR-v3 over Starlink LEO   ·   "
         "status update, 28 Aug 2026   ·   updated 4 Sep", 12, color=GREY)
    body = _tb(s, 1.20, 2.95, 10.9, 3.4).text_frame
    ps = [
        ("After closing an action-space exploit in the inflight_hi / inflight_lo heads, qbbr's "
         "behaviour across every extension we have tried — wider action space, risk-predictive "
         "state, parameter-matched quantum core, alpha-fair coexistence objective — converges to "
         "the same picture:", INK, False),
        ("London — a real, pre-registered improvement over stock BBR-v3:  -37% retransmits, "
         "p = 0.024, throughput retained 99.5%", GREEN, True),
        ("The other five sites, and every subsequent extension — fail the effect-size or the "
         "significance bar, without ever reversing direction", AMBER, True),
        ("Question for this meeting:  is this pattern itself the finding worth reporting — or a "
         "signal to change the framing / tools before we lock results?", BLUE, True),
    ]
    for i, (txt, col, b) in enumerate(ps):
        p = body.paragraphs[0] if i == 0 else body.add_paragraph()
        p.space_after = Pt(10)
        _run(p, txt, 13, color=col, bold=b)


def slide02(prs):
    s = new_slide(prs)
    header(s, "The setup: one control loop, four pre-registered levers")
    caption(s, "baseline — De Silva, Pokhrel & Kua, IEEE TMC (six-city Starlink measurement study)")
    pic(s, DECK / "image1.png", 0.45, 1.45, 7.2, 1096 / 559)
    bullets(s, 8.0, 1.7, 5.0, 5.2, [
        "BBR-v3 beats Cubic / Vegas / Hybla over Starlink, but pays a fixed, "
        "environment-agnostic probing budget (~2% loss·RTT)",
        "That retransmission cost varies ~42x across the six sites — worst at Sydney;  "
        "r = -0.78 with path RTT",
        "qbbr: can a learned agent adapt one lever, BBR-v3's pacing_gain, per environment?",
        "Four pre-registered levers: action (RQ1) · reward (RQ2) · state (RQ3) · core (RQ4).  "
        "10 seeds x 6 sites",
    ])
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=2))


def slide03(prs):
    s = new_slide(prs)
    header(s, "RQ1a — the one pre-registered win")
    caption(s, "retransmit reduction vs stock BBR-v3;  dotted line = 20% pre-registered threshold")
    pic(s, FIG / "bar_rq1_headline.png", 1.9, 1.5, 9.5, 1650 / 750)
    bullets(s, 0.6, 5.95, 12.2, 1.1, [
        "London: 37.1% fewer retransmits, p = 0.024, throughput retained 99.5%  ->  "
        "clears the pre-registered bar",
        "Other five sites: direction correct (all reductions positive) but 3.6-10.0%, "
        "none significant (p = 0.14-1.0)",
        "Widening the action space (inflight_hi/lo + freeze + EMA) lifts Tokyo to ~17%, "
        "moves no other site over the line",
    ])
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=3))


def slide04(prs):
    s = new_slide(prs)
    header(s, "The win is real and safe — it is just narrow")
    caption(s, "stock BBR-v3  vs  qbbr (pacing-only)  vs  qbbr (extended);  10 seeds / 10 trace-files per box")
    pic(s, FIG / "boxplot_rq1_vs_bbr.png", 0.5, 1.45, 5.4, 1.0)
    bullets(s, 6.3, 1.7, 6.5, 5.0, [
        "Throughput within 99-104% of stock at every site — never the binding constraint",
        "RTT 2-7% lower at every site, mostly p < 0.001  (uplink and downlink)",
        "Retransmit median lower at all six, but the gap only clears 20% + significance at London",
        "   – simulator tracks throughput / RTT / retransmits, not cwnd or rwnd",
        "   – qbbr boxes tight (seed noise);  BBR-v3 boxes wide (real-trace heterogeneity)",
    ])
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=4))


def slide05(prs):
    s = new_slide(prs)
    header(s, "The action-space exploit we found and closed")
    caption(s, "left: why the reward could not see it   ·   right: behaviour once each head is on its native range")
    pic(s, DECK / "image4.png", 0.30, 1.45, 12.7, 4078 / 760)
    bullets(s, 0.6, 4.15, 12.2, 2.9, [
        "With symmetric inflight_hi/lo heads the agent shrank both below stock BBR-v3 defaults — "
        "a marginal per-step RTT gain the reward sees every step...",
        "...paid for with a persistently elevated retransmit rate the reward's delta-only loss "
        "term stops seeing once that rate stabilizes  (left: loss term falls under throttle)",
        "Fixed: heads restricted to their native expansion-only range.  Re-run under native "
        "ranges, the exploit behaviour is gone (right)",
        "Every extension result in this deck is on the clean action space",
    ])
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=5))


def slide06(prs):
    s = new_slide(prs)
    header(s, "Every wider lever converges to the same picture")
    caption(s, "RQ2 alpha-fair reward (left)   ·   RQ3 risk-predictive state (right)   ·   RQ4 in the scorecard")
    pic(s, FIG / "line_rq2_alpha_sweep.png", 0.4, 1.42, 6.7, 2250 / 1125)
    pic(s, FIG / "bar_rq3_risk_toggle.png", 7.5, 1.95, 5.5, 1950 / 750)
    bullets(s, 0.6, 4.78, 12.4, 2.2, [
        "RQ2 — alpha-fair reward, coexistence: rho_alpha tracks stock across the whole sweep;  "
        "Delta is 0.05-0.17% of rho;  5/6 in the rewarded direction, Sydney opposite",
        "RQ3 — risk-predictive state (s5/s6): risk-on vs risk-off within noise, p >= 0.43;  also "
        "null under a fuller atmospheric + ISL + handover risk feature (p_rtx >= 0.68)  ->  "
        "demoted to ablation-only",
        "RQ4 — quantum vs an exact 126-parameter full-agent-matched classical core (seven-input): "
        "indistinguishable, p >= 0.47, n=10;  reproduces the archived six-input null (appendix A2)",
    ], size=11.5)
    footer(s, FOOT_MAIN.format(date="updated 4 Sep 2026", n=6))


def slide07(prs):
    s = new_slide(prs)
    header(s, "Tried post-hoc, reported retracted: boundary-freeze")
    caption(s, "freezing the action around the 15 s handover reconfiguration")
    pic(s, FIG / "bar_shifted_freeze.png", 0.35, 1.5, 6.4, 1650 / 750)
    pic(s, FIG / "line_anticipatory_vs_decoy_lag.png", 7.0, 1.5, 6.0, 2250 / 1125)
    bullets(s, 0.6, 4.7, 12.3, 2.3, [
        "Motivation held (left): ~44% of retransmits fall in a window that is 13% of episode time",
        "Decoy-phase control (left bars): real calibrated phase vs 5 decoy offsets -> "
        "Delta -3% to +3%, p = 0.42-0.82 at all six sites",
        "Lead / lag scripted-throttle control (right): the reduction comes from throttling at all, "
        "not from timing",
        "Reported as retracted;  effect is 1-2 pp either way, inside the real-trace noise floor.  "
        "Pre-registered replication is future work",
    ])
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=7))


def slide08(prs):
    s = new_slide(prs)
    header(s, "Where we are — and the question for you")
    pic(s, FIG / "scorecard.png", 0.5, 1.15, 12.35, 2040 / 607)
    box = s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.55), Inches(5.05),
                             Inches(12.25), Inches(2.0))
    box.fill.solid()
    box.fill.fore_color.rgb = CALLOUT_BG
    box.line.fill.background()
    box.shadow.inherit = False
    tf = _tb(s, 0.85, 5.16, 11.7, 1.8).text_frame
    lines = [
        ("Pattern:  one narrow win under pacing_gain alone;  no wider lever (action space, state, "
         "core, reward) extends it;  no site ever reverses direction.", INK, True),
        ("Q1 — Is \"a single lever has a narrow, site-specific effect and nothing generalises it\" "
         "itself the reportable finding?", BLUE, False),
        ("Q2 — Or is this the point to change framing / tools before results lock  "
         "(different action target · multi-site training · real-testbed guardrail · uplink scope)?",
         BLUE, False),
        ("Revised, expanded question set on slide 13.", GREY, False),
    ]
    for i, (txt, col, b) in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(4)
        _run(p, txt, 10.5, color=col, bold=b)
    footer(s, FOOT_MAIN.format(date="28 Aug 2026", n=8))


def slide09(prs):
    s = new_slide(prs)
    header(s, "Appendix A1 — exploit closed: behaviour under native action ranges")
    caption(s, "mean inflight level minus each arm's own default;  exploit vs fixed checkpoint, 5 seeds/site")
    pic(s, FIG / "bar_ecn_behavior_shift.png", 1.15, 1.45, 11.0, 1950 / 750)
    bullets(s, 0.6, 5.9, 12.3, 1.2, [
        "'fixed' arm sits at its expansion-only default (+0.5 / +0.24 B_DP);  'exploit' arm ~ 0 "
        "once replayed on its native range",
        "confirms the sub-default shrink was an artifact of the symmetric range, not learned policy",
    ])
    footer(s, FOOT_APX.format(date="28 Aug 2026"))


def slide10(prs):
    s = new_slide(prs)
    header(s, "Appendix A2 — RQ4: quantum vs parameter-matched classical (seven-input)")
    caption(s, "final-episode reward per core;  exact 126-parameter full-agent match;  "
               "10 seeds/site,  alpha=1, L=2")
    pic(s, FIG / "rq4_quantum_vs_classical.png", 1.85, 1.45, 9.6, 1950 / 810)
    bullets(s, 0.6, 5.65, 12.3, 1.5, [
        "clouds overlap at every site — Mann-Whitney p >= 0.47, n=10;  every gap well under a "
        "core's own seed IQR",
        "reproduces the archived six-input null (p >= 0.19);  sign of the sub-IQR gap flips "
        "6 -> 7 input (bottom panel)",
        "one grid point (alpha=1, L=2, no re-uploading);  L=3 ~1-2 days/cell on lightning.qubit, "
        "not yet run",
    ])
    footer(s, FOOT_APX.format(date="updated 4 Sep 2026"))


def slide11(prs):
    s = new_slide(prs)
    header(s, "Appendix A3 — boundary-freeze: full mechanism controls")
    caption(s, "left: decoy-phase control (real vs 5 shifted phases)   ·   right: scripted-throttle lead vs lag sweep")
    pic(s, FIG / "bar_shifted_freeze.png", 0.35, 1.5, 6.4, 1650 / 750)
    pic(s, FIG / "line_anticipatory_vs_decoy_lag.png", 7.0, 1.5, 6.0, 2250 / 1125)
    bullets(s, 0.6, 4.7, 12.3, 1.5, [
        "no phase-specific signal: real calibrated phase indistinguishable from pooled decoys at "
        "all six sites (p 0.42-0.82)",
        "lead and lag give the same large reduction -> effect is 'throttle at all', not "
        "anticipation;  Sydney the one exception",
    ])
    footer(s, FOOT_APX.format(date="28 Aug 2026"))


def slide12(prs):
    s = new_slide(prs)
    header(s, "Update (4 Sep) — RQ4 closed at seven-input")
    caption(s, "since the 28 Aug status: RQ4 run at protocol  ·  RQ3 null re-confirmed  ·  faster quantum backend")
    pic(s, FIG / "rq4_quantum_vs_classical.png", 1.95, 1.35, 9.4, 1950 / 810)
    bullets(s, 0.62, 5.45, 12.1, 1.7, [
        "RQ4: quantum vs an exact 126-parameter full-agent-matched classical core (seven-input, "
        "alpha = 1, L = 2) — null at every site, Mann-Whitney p >= 0.47, n = 10; reproduces the "
        "archived six-input null (p >= 0.19). Draft caveat “needs a fresh matched "
        "evaluation” is resolved.",
        "RQ3: the s5 / s6 null also holds under a fuller risk feature (atmospheric + ISL + "
        "handover hazard), p_rtx >= 0.68 — not just the atmospheric constant.",
        "Backend: lightning.qubit — 2.2x faster, verified numerically identical (fwd + grad to "
        "~1e-7); parallel RQ4 runner added. RQ4 L = 3 now ~1-2 days / cell, not a week.",
    ], size=11.5)
    footer(s, FOOT_UPD)


def slide13(prs):
    s = new_slide(prs)
    header(s, "Revised questions for you")
    caption(s, "all four RQs now answered at the pre-registered protocol; headline unchanged — mostly null / qualified-no")
    bullets(s, 0.62, 1.7, 12.1, 5.2, [
        "Q1 — the real gate: does this mostly-null, pre-registered result satisfy SIT723 / 792 as "
        "the project outcome?",
        "Q2 — RQ2 scope: the reported RQ2 transfers an isolation-trained alpha-fair policy into "
        "coexistence (a qualified no). Training directly on the multi-flow alpha-fair reward — the "
        "literal RQ2 — is a ~12-24 h run I can start now; or report transfer-only with the gap "
        "disclosed. Which?",
        "Q3 — RQ4 grid: L = 3 / data re-uploading is now feasible (~1-2 days / cell). Run it, or "
        "freeze at L = 2 and report as a scoped limitation?",
        "Proceeding under the current draft unless you object: title “The Limits of a Single "
        "Lever” (provisional); the gamma = 5.0 reward-scale finding in Discussion as a "
        "post-hoc complication; the “single lever” cross-RQ reading in Discussion, not "
        "the Intro.",
    ], size=12)
    footer(s, FOOT_UPD)


def main():
    prs = Presentation()
    prs.slide_width, prs.slide_height = EMU_W, EMU_H
    for fn in (slide01, slide02, slide03, slide04, slide05, slide06, slide07,
               slide08, slide09, slide10, slide11, slide12, slide13):
        fn(prs)
    prs.save(str(OUT))
    print(f"saved {OUT}  ({len(prs.slides)} slides)")


if __name__ == "__main__":
    main()
